// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: parser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParseAutoBattlerService_GetAutobattlerTable_FullMethodName = "/server.ParseAutoBattlerService/GetAutobattlerTable"
)

// ParseAutoBattlerServiceClient is the client API for ParseAutoBattlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Определение сервиса парсинга авттобаллера
type ParseAutoBattlerServiceClient interface {
	GetAutobattlerTable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AutobattlerTable, error)
}

type parseAutoBattlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParseAutoBattlerServiceClient(cc grpc.ClientConnInterface) ParseAutoBattlerServiceClient {
	return &parseAutoBattlerServiceClient{cc}
}

func (c *parseAutoBattlerServiceClient) GetAutobattlerTable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AutobattlerTable, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutobattlerTable)
	err := c.cc.Invoke(ctx, ParseAutoBattlerService_GetAutobattlerTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParseAutoBattlerServiceServer is the server API for ParseAutoBattlerService service.
// All implementations must embed UnimplementedParseAutoBattlerServiceServer
// for forward compatibility.
//
// Определение сервиса парсинга авттобаллера
type ParseAutoBattlerServiceServer interface {
	GetAutobattlerTable(context.Context, *emptypb.Empty) (*AutobattlerTable, error)
	mustEmbedUnimplementedParseAutoBattlerServiceServer()
}

// UnimplementedParseAutoBattlerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParseAutoBattlerServiceServer struct{}

func (UnimplementedParseAutoBattlerServiceServer) GetAutobattlerTable(context.Context, *emptypb.Empty) (*AutobattlerTable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAutobattlerTable not implemented")
}
func (UnimplementedParseAutoBattlerServiceServer) mustEmbedUnimplementedParseAutoBattlerServiceServer() {
}
func (UnimplementedParseAutoBattlerServiceServer) testEmbeddedByValue() {}

// UnsafeParseAutoBattlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParseAutoBattlerServiceServer will
// result in compilation errors.
type UnsafeParseAutoBattlerServiceServer interface {
	mustEmbedUnimplementedParseAutoBattlerServiceServer()
}

func RegisterParseAutoBattlerServiceServer(s grpc.ServiceRegistrar, srv ParseAutoBattlerServiceServer) {
	// If the following call pancis, it indicates UnimplementedParseAutoBattlerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParseAutoBattlerService_ServiceDesc, srv)
}

func _ParseAutoBattlerService_GetAutobattlerTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParseAutoBattlerServiceServer).GetAutobattlerTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParseAutoBattlerService_GetAutobattlerTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParseAutoBattlerServiceServer).GetAutobattlerTable(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ParseAutoBattlerService_ServiceDesc is the grpc.ServiceDesc for ParseAutoBattlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParseAutoBattlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.ParseAutoBattlerService",
	HandlerType: (*ParseAutoBattlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAutobattlerTable",
			Handler:    _ParseAutoBattlerService_GetAutobattlerTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parser.proto",
}

const (
	ParseDialogService_GetDialogTable_FullMethodName = "/server.ParseDialogService/GetDialogTable"
)

// ParseDialogServiceClient is the client API for ParseDialogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParseDialogServiceClient interface {
	GetDialogTable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TaskList, error)
}

type parseDialogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParseDialogServiceClient(cc grpc.ClientConnInterface) ParseDialogServiceClient {
	return &parseDialogServiceClient{cc}
}

func (c *parseDialogServiceClient) GetDialogTable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, ParseDialogService_GetDialogTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParseDialogServiceServer is the server API for ParseDialogService service.
// All implementations must embed UnimplementedParseDialogServiceServer
// for forward compatibility.
type ParseDialogServiceServer interface {
	GetDialogTable(context.Context, *emptypb.Empty) (*TaskList, error)
	mustEmbedUnimplementedParseDialogServiceServer()
}

// UnimplementedParseDialogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParseDialogServiceServer struct{}

func (UnimplementedParseDialogServiceServer) GetDialogTable(context.Context, *emptypb.Empty) (*TaskList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogTable not implemented")
}
func (UnimplementedParseDialogServiceServer) mustEmbedUnimplementedParseDialogServiceServer() {}
func (UnimplementedParseDialogServiceServer) testEmbeddedByValue()                            {}

// UnsafeParseDialogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParseDialogServiceServer will
// result in compilation errors.
type UnsafeParseDialogServiceServer interface {
	mustEmbedUnimplementedParseDialogServiceServer()
}

func RegisterParseDialogServiceServer(s grpc.ServiceRegistrar, srv ParseDialogServiceServer) {
	// If the following call pancis, it indicates UnimplementedParseDialogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParseDialogService_ServiceDesc, srv)
}

func _ParseDialogService_GetDialogTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParseDialogServiceServer).GetDialogTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParseDialogService_GetDialogTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParseDialogServiceServer).GetDialogTable(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ParseDialogService_ServiceDesc is the grpc.ServiceDesc for ParseDialogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParseDialogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.ParseDialogService",
	HandlerType: (*ParseDialogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDialogTable",
			Handler:    _ParseDialogService_GetDialogTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parser.proto",
}
