// Code generated by MockGen. DO NOT EDIT.
// Source: sheet_wrapper.go

// Package parser is a generated GoMock package.
package parser

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	xlsx "github.com/tealeg/xlsx"
)

// MockSheetWrapper is a mock of SheetWrapper interface.
type MockSheetWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockSheetWrapperMockRecorder
}

// MockSheetWrapperMockRecorder is the mock recorder for MockSheetWrapper.
type MockSheetWrapperMockRecorder struct {
	mock *MockSheetWrapper
}

// NewMockSheetWrapper creates a new mock instance.
func NewMockSheetWrapper(ctrl *gomock.Controller) *MockSheetWrapper {
	mock := &MockSheetWrapper{ctrl: ctrl}
	mock.recorder = &MockSheetWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheetWrapper) EXPECT() *MockSheetWrapperMockRecorder {
	return m.recorder
}

// Rows mocks base method.
func (m *MockSheetWrapper) Rows() []*xlsx.Row {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rows")
	ret0, _ := ret[0].([]*xlsx.Row)
	return ret0
}

// Rows indicates an expected call of Rows.
func (mr *MockSheetWrapperMockRecorder) Rows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rows", reflect.TypeOf((*MockSheetWrapper)(nil).Rows))
}
